### ISSUE TITLE
move 《超算竞赛导引》 to the blog

### ISSUE THREAD

**Issue by TideDra** [CSWU-Challenge/CSWU-Challenge.github.io#15]
move 《超算竞赛导引》 to the blog

**Comment by JohnG-mit** [comment]
这需要购买正版pdf吧🙀，而且正版pdf多半不能下载

**Comment by TideDra** [comment]
> 这需要购买正版pdf吧🙀，而且正版pdf多半不能下载

所以手动OCR是一项不小的工程

**Comment by JohnG-mit** [comment]
> > 这需要购买正版pdf吧🙀，而且正版pdf多半不能下载
> 
> 所以手动OCR是一项不小的工程

那不就侵权了吗，我们这个以后是要对外开放的

**Comment by TideDra** [comment]
> 那不就侵权了吗，我们这个以后是要对外开放的

可以“借鉴”、“转述”一些有用的内容

**Comment by haoruilee** [comment]
> > 那不就侵权了吗，我们这个以后是要对外开放的
> 
> 可以“借鉴”、“转述”一些有用的内容

感觉这本书里有用的内容其实不多

**Comment by TideDra** [comment]
> 感觉这本书里有用的内容其实不多

所以还要我们自己补充
