### ISSUE TITLE
入门流程

### ISSUE THREAD

**Issue by Ypsxc111** [CSWU-Challenge/CSWU-Challenge.github.io#25]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/CSWU-Challenge/CSWU-Challenge.github.io/blob/master/CONTRIBUTION.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

希望可以拟出一份，从小白到入门的思维流程导图，这样我感觉可以省去不少的工作，也有利于像我这样的小白自主学习。

### Use Cases

我觉得，就是相当于学习过程中的一个路标性指引，不必太详细，但是确实会带来指导性作用

### Screenshots / Mockups

无

**Comment by haoruilee** [comment]
关于SC22我们在[FAQ板块](https://github.com/CSWU-Challenge/CSWU-Challenge.github.io/issues/new?assignees=&labels=help+wanted%2Cgood+first+issue&template=FAQ.yml)增加了一些前置引导

**Comment by haoruilee** [comment]
> 关于SC22我们在[FAQ板块](https://github.com/CSWU-Challenge/CSWU-Challenge.github.io/issues/new?assignees=&labels=help+wanted%2Cgood+first+issue&template=FAQ.yml)增加了一些前置引导

虽然你的这个问题不是SC22专属，不过还是希望后面的同学使用新模板提issue

**Comment by TideDra** [comment]
关于这个问题，请详细阅读东南大学超算平台的《超算竞赛快速入门》，上面指出了入门超算需要必备哪些知识和技能。实际上参加超算竞赛更需要的是动手操作的技能和解决问题的经验，没有成体系的知识，或者说，他需要的知识非常零碎，许多东西需要实时查阅资料，所以不用刻意地学什么。新手不必担心自己一无所知，只要能自主坚持走完环境搭建与应用优化的流程，基本就是入门了。而这个过程最需要的是使用搜索引擎的能力。

**Comment by haoruilee** [comment]
sc22校赛已结束，祝取得优异成绩，另外欢迎参与asc-wiki的社区建设！
