### ISSUE TITLE
start

### ISSUE THREAD

**Issue by Ypsxc111** [CSWU-Challenge/CSWU-Challenge.github.io#26]
### 入门指导

- [X] 我已经阅读了[超算竞赛快速入门](https://cswu-challenge.github.io/wiki/ASC-introduction/)、[2022超算竞赛手册](https://qiniuyun.hrlee.cn/%E7%AB%9E%E8%B5%9B%E6%89%8B%E5%86%8C%E4%B9%8BASC%E8%B6%85%E7%AE%97.pdf)、[吴院竞赛指导-李浩瑞](https://qiniuyun.hrlee.cn/%E5%90%B4%E9%99%A2%E7%AB%9E%E8%B5%9B%E6%8C%87%E5%AF%BC-%E6%9D%8E%E6%B5%A9%E7%91%9E.pptx)以及该板块下的其他问题。

### 外校资源

- [X] 资源：[中山大学队长博客](https://wu-kan.cn/tags/)，[上海大学队长博客](https://henryavery.cn/2021/06/17/asc2022/)，[上海交大超算平台用户文档](https://docs.hpc.sjtu.edu.cn/index.html)，[卢森堡大学超算教程](https://ulhpc-tutorials.readthedocs.io/en/latest/)。

### 问题描述

目前还没有问题，可能时间有点紧张

**Comment by haoruilee** [comment]
有问题的时候再单独开issue

另外如果对github使用比较熟悉，可以参考其他 ~help-wanted 的issue 比如 #24 并参与贡献
