### ISSUE TITLE
Use GPU in WMware

### ISSUE THREAD

**Issue by zombie11135** [CSWU-Challenge/CSWU-Challenge.github.io#27]
### 入门指导

- [X] 我已经阅读了[超算竞赛快速入门](https://cswu-challenge.github.io/wiki/ASC-introduction/)、[2022超算竞赛手册](https://qiniuyun.hrlee.cn/%E7%AB%9E%E8%B5%9B%E6%89%8B%E5%86%8C%E4%B9%8BASC%E8%B6%85%E7%AE%97.pdf)、[吴院竞赛指导-李浩瑞](https://qiniuyun.hrlee.cn/%E5%90%B4%E9%99%A2%E7%AB%9E%E8%B5%9B%E6%8C%87%E5%AF%BC-%E6%9D%8E%E6%B5%A9%E7%91%9E.pptx)以及该板块下的其他问题。

### 外校资源

- [ ] 资源：[中山大学队长博客](https://wu-kan.cn/tags/)，[上海大学队长博客](https://henryavery.cn/2021/06/17/asc2022/)，[上海交大超算平台用户文档](https://docs.hpc.sjtu.edu.cn/index.html)，[卢森堡大学超算教程](https://ulhpc-tutorials.readthedocs.io/en/latest/)。

### 问题描述

安装了linux虚拟机（Vmware平台，Ubuntu 20.04.3） 在搜索如何安装显卡驱动程序时看到虚拟机无法安装英伟达的显卡驱动以及CUDA，请问对完成HPL等任务是否有影响呢？多谢！

**Comment by Gfssfa** [comment]
据我了解，VM+ubuntu能用显卡，应该需要配置驱动，用到显卡的话找平台租卡应该方便些。HPL测试可以不用显卡只CPU，当然我们也欢迎多平台的实验。

**Comment by zsa2001** [comment]
使用虚拟机确实无法使用显卡，不过对于HPL等测试任务我们不将gpu测试作为必选项，完成cpu测试即可获得基本分数；有时间的话可以优先考虑完成其他任务。

**Comment by haoruilee** [comment]
sc22校赛已结束，祝取得优异成绩，另外欢迎参与asc-wiki的社区建设！
