### ISSUE TITLE
安装调试MPI时关于环境变量PATH设置的问题

### ISSUE THREAD

**Issue by zombie11135** [CSWU-Challenge/CSWU-Challenge.github.io#28]
### 入门指导

- [X] 我已经阅读了[超算竞赛快速入门](https://cswu-challenge.github.io/wiki/ASC-introduction/)、[2022超算竞赛手册](https://qiniuyun.hrlee.cn/%E7%AB%9E%E8%B5%9B%E6%89%8B%E5%86%8C%E4%B9%8BASC%E8%B6%85%E7%AE%97.pdf)、[吴院竞赛指导-李浩瑞](https://qiniuyun.hrlee.cn/%E5%90%B4%E9%99%A2%E7%AB%9E%E8%B5%9B%E6%8C%87%E5%AF%BC-%E6%9D%8E%E6%B5%A9%E7%91%9E.pptx)以及该板块下的其他问题。

### 外校资源

- [ ] 资源：[中山大学队长博客](https://wu-kan.cn/tags/)，[上海大学队长博客](https://henryavery.cn/2021/06/17/asc2022/)，[上海交大超算平台用户文档](https://docs.hpc.sjtu.edu.cn/index.html)，[卢森堡大学超算教程](https://ulhpc-tutorials.readthedocs.io/en/latest/)。

### 问题描述

安装MPI时一开始安装路径和PATH的设置路径都没有设置在/usr/local中，而是新建了一个文件夹，是导致在检查安装情况时which mpirun等出错的原因吗？但在另外的检验，也就是运行example中的hellow程序时，在mpirun前加上命令的绝对路径是可以正常执行的，这样安装成功了吗？多谢！

### 你的学号

61821209

**Comment by JohnG-mit** [comment]
添加环境变量最简单粗暴的方法就是找到对应软件的二进制可执行文件加入PATH。Linux中的文件安装更像是一个解压的过程，它通过configure脚本将一些需要的依赖链接好之后解压到你指定的安装路径。安装任何软件，如果没有提供一键化自动配置环境脚本，都需要手动添加环境变量以保证软件能够运行。

**Comment by haoruilee** [comment]
sc22校赛已结束，祝取得优异成绩，另外欢迎参与asc-wiki的社区建设！
