### ISSUE TITLE
MPI报错：your application terminated with the exit string: segmentation fault (signal 11)

### ISSUE THREAD

**Issue by Pounding-Heart** [CSWU-Challenge/CSWU-Challenge.github.io#30]
### 入门指导

- [X] 我已经阅读了[超算竞赛快速入门](https://cswu-challenge.github.io/wiki/ASC-introduction/)、[2022超算竞赛手册](https://qiniuyun.hrlee.cn/%E7%AB%9E%E8%B5%9B%E6%89%8B%E5%86%8C%E4%B9%8BASC%E8%B6%85%E7%AE%97.pdf)、[吴院竞赛指导-李浩瑞](https://qiniuyun.hrlee.cn/%E5%90%B4%E9%99%A2%E7%AB%9E%E8%B5%9B%E6%8C%87%E5%AF%BC-%E6%9D%8E%E6%B5%A9%E7%91%9E.pptx)以及该板块下的其他问题。

### 外校资源

- [X] 资源：[中山大学队长博客](https://wu-kan.cn/tags/)，[上海大学队长博客](https://henryavery.cn/2021/06/17/asc2022/)，[上海交大超算平台用户文档](https://docs.hpc.sjtu.edu.cn/index.html)，[卢森堡大学超算教程](https://ulhpc-tutorials.readthedocs.io/en/latest/)。

### 问题描述

使用`mpirun -np 10 ./examples/cpi`测试MPICH时出现错误your application terminated with the exit string: segmentation fault (signal 11)     并且我自己写了cpp文件用mpi编译运行时会出现同样的错误。
google出来的答案很少，也没找到具体解决方案。是不是我的ubuntu和MPICH版本不兼容？MPICH版本是4.0.2，ubuntu是16.
求解答，谢谢！

### 你的学号

61821224

**Comment by TideDra** [comment]
你这个np的值有点奇怪？-np参数必须等于配置文件中P*Q的值，并且不能超过cpu最大线程数。另外请贴出全部报错信息以及所用的配置文件以及相关代码。

**Comment by Pounding-Heart** [comment]
报错信息：
`chenxb@chenxb-virtual-machine:~$ which mpic++
/home/chenxb/Desktop/mpich-install/bin/mpic++
chenxb@chenxb-virtual-machine:~$ cd Desktop
chenxb@chenxb-virtual-machine:~/Desktop$ touch test.cpp
chenxb@chenxb-virtual-machine:~/Desktop$ mpic++ -o test test.cpp
chenxb@chenxb-virtual-machine:~/Desktop$ mpirun -np 4./test

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 7780 RUNNING AT chenxb-virtual-machine
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
`

test.cpp中代码：
`#include <mpi.h>
#include <iostream>

using namespace std;

int main (int argc, char **argv)
{
    int myid, numprocs;
    MPI_Init (&argc, &argv);
    MPI_Comm_rank (MPI_COMM_WORLD, &myid);
    MPI_Comm_size (MPI_COMM_WORLD, &numprocs);
    cout<<"Hello from process_"<<myid<<endl;
    MPI_Finalize();
    return 0;
}`

不过重启之后   这个`mpirun -np 10 ./examples/cpi`倒是可以正常输出了   -np参数我是按google中来的 不是很理解 但可以用

**Comment by TideDra** [comment]
你这是个人电脑上的虚拟机吧，那cpu线程数应该到不了10。调整hpl配置文件参数，不要超过最大线程数。

**Comment by Pounding-Heart** [comment]
那上方的这个是 `mpirun -np 4./test`   为什么不行呢   N调到1也不行欸

**Comment by Pounding-Heart** [comment]
> 那上方的这个是 `mpirun -np 4./test` 为什么不行呢 N调到1也不行欸

这个`mpirun -np 10 ./examples/cpi`倒反而OK

**Comment by JohnG-mit** [comment]
> > 那上方的这个是 `mpirun -np 4./test` 为什么不行呢 N调到1也不行欸
> 
> 这个`mpirun -np 10 ./examples/cpi`倒反而OK

P x Q的值和你mpirun -np的数值相同吗？

**Comment by JohnG-mit** [comment]
> > 那上方的这个是 `mpirun -np 4./test` 为什么不行呢 N调到1也不行欸
> 
> 这个`mpirun -np 10 ./examples/cpi`倒反而OK

![image](https://user-images.githubusercontent.com/98368355/163682610-aaaea2b5-f897-4979-b0e5-06102716ccb5.png)
这是我复制你的test代码，我注意到你并没有引入iostream头文件，这样可以编译成功吗？
我在成功编译之后运行是可以正常输出的：
![image](https://user-images.githubusercontent.com/98368355/163682671-c797c311-daf8-46ca-b515-1fc87e99dc1d.png)
不知道具体是出了什么问题。这样的基础MPI程序不应该涉及到兼容性和版本问题。

**Comment by Pounding-Heart** [comment]
make clean后已经解决了！ 可能也和之前代码书写不规范有关系 谢谢！
